<a href="https://colab.research.google.com/github/wtryab-re/machine-learning-reboost/blob/main/Data_Collection_n_Loading_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Install the Libraries

In [2]:
!pip install -q pandas numpy seaborn matplotlib

pyarrow are used for parquet files

Parquet files are used when the data is extremely large, so it compresses it.

openpyxl are used for excel files
used for excel sheet manipulation, NOT like pandas at all.

Pandas used for analysis work only

In [12]:
!pip install -q pyarrow openpyxl

Import the Libraries

In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

##Titanic(1) CSV

In [42]:
titanic_dataset = pd.read_csv("titanic (1).csv")
titanic_dataset.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Load selected columns

In [41]:
titanic_dataset_selected = pd.read_csv("titanic (1).csv", usecols=["PassengerId"])
titanic_dataset_selected.head(2)

   PassengerId
0            1
1            2

Load selected rows

In [40]:
titanic_dataset_selected = pd.read_csv("titanic (1).csv", nrows=20)
titanic_dataset_selected.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Titanic Tab CSV

In [43]:
titanic_tab = pd.read_csv("/content/titanic_tab.csv",sep="\t")
titanic_tab.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Excel

In [37]:
titanic_excel = pd.read_excel("/content/titanic.xlsx")
titanic_excel.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Load selected columns

In [36]:
titanic_excel_selected = pd.read_excel("/content/titanic.xlsx", usecols=["PassengerId"])
titanic_excel_selected.head(2)

   PassengerId
0            1
1            2

Load Selected Rows

In [35]:
titanic_excel_selected = pd.read_excel("/content/titanic.xlsx", nrows=20)
titanic_excel_selected.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Select Specific Sheet in Excel

In [30]:
#sheet names
excel_sheet = pd.ExcelFile("titanic.xlsx")
excel_sheet.sheet_names

['Sheet1']

In [34]:
#open w the sheet name
titanic_excel_sheet = pd.read_excel(excel_sheet, sheet_name="Sheet1")
titanic_excel_sheet.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Titanic Parquet
Parquet files are used when the data is extremely large, so it compresses it.

In [38]:
titanic_parquet = pd.read_parquet("/content/titanic.parquet")
titanic_parquet.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

#Check file sizes

In [48]:
file_size = os.stat("titanic.xlsx").st_size
print(f"Size: {file_size} bytes")

Size: 68829 bytes