<a href="https://colab.research.google.com/github/wtryab-re/machine-learning-reboost/blob/main/Data_Collection_n_Loading_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Install the Libraries

In [ ]:
!pip install -q pandas numpy seaborn matplotlib

pyarrow are used for parquet files

Parquet files are used when the data is extremely large, so it compresses it.

openpyxl are used for excel files
used for excel sheet manipulation, NOT like pandas at all.

Pandas used for analysis work only

In [ ]:
!pip install -q pyarrow openpyxl

Import the Libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

##Titanic(1) CSV

In [ ]:
titanic_dataset = pd.read_csv("titanic (1).csv")
titanic_dataset.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Load selected columns

In [ ]:
titanic_dataset_selected = pd.read_csv("titanic (1).csv", usecols=["PassengerId"])
titanic_dataset_selected.head(2)

   PassengerId
0            1
1            2

Load selected rows

In [ ]:
titanic_dataset_selected = pd.read_csv("titanic (1).csv", nrows=20)
titanic_dataset_selected.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Titanic Tab CSV

In [ ]:
titanic_tab = pd.read_csv("/content/titanic_tab.csv",sep="\t")
titanic_tab.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Excel

In [ ]:
titanic_excel = pd.read_excel("/content/titanic.xlsx")
titanic_excel.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Load selected columns

In [ ]:
titanic_excel_selected = pd.read_excel("/content/titanic.xlsx", usecols=["PassengerId"])
titanic_excel_selected.head(2)

   PassengerId
0            1
1            2

Load Selected Rows

In [ ]:
titanic_excel_selected = pd.read_excel("/content/titanic.xlsx", nrows=20)
titanic_excel_selected.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Select Specific Sheet in Excel

In [ ]:
#sheet names
excel_sheet = pd.ExcelFile("titanic.xlsx")
excel_sheet.sheet_names

['Sheet1']

In [ ]:
#open w the sheet name
titanic_excel_sheet = pd.read_excel(excel_sheet, sheet_name="Sheet1")
titanic_excel_sheet.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

##Titanic Parquet
Parquet files are used when the data is extremely large, so it compresses it.

In [ ]:
titanic_parquet = pd.read_parquet("/content/titanic.parquet")
titanic_parquet.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

#Check file sizes

In [ ]:
file_size = os.stat("titanic.xlsx").st_size
print(f"Size: {file_size} bytes")

Size: 68829 bytes

#Kaggle

oh kaggle pisses me off, its so complex for NO reason

##Kaggle

Way 1 to download kaggle datasets

In [ ]:
!pip install -q kagglehub[pandas-datasets]

In [ ]:
# Install dependencies as needed:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "annual-number-of-deaths-by-cause.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "programmerrdai/cancer",
  file_path
)

##Way 2

In [ ]:
!kaggle datasets download programmerrdai/cancer

Dataset URL: https://www.kaggle.com/datasets/programmerrdai/cancer
License(s): CC0-1.0
Downloading cancer.zip to /content
100% 7.84M/7.84M [00:01<00:00, 5.84MB/s]

In [ ]:
import zipfile

In [ ]:
fil = zipfile.ZipFile("cancer.zip","r")
fil.extractall("/content")
fil.close()

##UCI Datasets

In [ ]:
!pip install -q ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
wine_quality = fetch_ucirepo(id=186)

# data (as pandas dataframes)
X = wine_quality.data.features
y = wine_quality.data.targets

# metadata
print(wine_quality.metadata)

# variable information
print(wine_quality.variables)

##API TOKEN SAVING

In [ ]:
import os

In [ ]:
os.environ["Kaggle_User"] = "CUZIALWAYSHADAVISIONOFUSSTANDINGLIKETHIS"

##Database Retrieval

When getting data from a DB

 Install any Relational DB Server

Install Dbeaver

In [ ]:
#installings if using postgres
!pip install -q SQLAlchemy psycopg2-binary

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
connection_string = "postgresql://username:password@host:port/dbname"
engine = create_engine(connection_string)

In [ ]:
df = pd.read_sql(
    sql="SELECT * FROM table_name",
    con=engine
)

#JSON/SQL FORMAT DATA

In [ ]:
!kaggle datasets download nurahmed12/json-dataset

Dataset URL: https://www.kaggle.com/datasets/nurahmed12/json-dataset
License(s): unknown
Downloading json-dataset.zip to /content
100% 1.80M/1.80M [00:01<00:00, 1.59MB/s]

In [9]:
import zipfile
import pandas as pd
unzip = zipfile.ZipFile("json-dataset.zip", "r")

In [14]:
unzip.extractall("data/")
unzip.close()

In [12]:
df = pd.read_json("data/train.json")
df.head()
df.shape

(39774, 3)

In [ ]:
pd.read_json("add an api link and it works the SAME")

##SQL

In [13]:
!kaggle datasets download hashtagkehl/worldsql

Dataset URL: https://www.kaggle.com/datasets/hashtagkehl/worldsql
License(s): unknown
Downloading worldsql.zip to /content
100% 787/787 [00:00<00:00, 2.45MB/s]

In [15]:
import zipfile
fil = zipfile.ZipFile("worldsql.zip", "r")
fil.extractall("data/")
fil.close()

In [ ]:
!pip install mysql.connector
import mysql.connector
conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "password",
    database = "world"
)

df = pd.read_sql_query("SELECT * FROM COUNTRY WHERE X = 10", conn)

##API - getting data from an api

In [59]:
!pip install -q requests

In [100]:
import requests
import os
import pandas as pd

url = "https://api.themoviedb.org/3/tv/top_rated?language=en-US&page=1"
os.environ["TMDBRATOKEN"]= "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1NDA4Y2I3ZjU2ZTk4MmU1MGI0ODc2ZTdhNzQ3ZmZlNSIsIm5iZiI6MTc0MTcxODM0MC4wNjcwMDAyLCJzdWIiOiI2N2QwODM0NDQzNGM5OGM4ZWM4MTNmMjAiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.Mdwpk-Uk9s0iYA90z_19lBB3qpPAHKBh0aUhZ5Ifu4M"
headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {os.environ["TMDBRATOKEN"]}" }

In [ ]:
response = requests.get(url, headers=headers)
data = response.json()
df = pd.DataFrame(data["results"],columns=["id", "name", "overview", "first_air_date", "vote_count", "vote_average"])
data["results"]

In [115]:
headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {os.environ["TMDBRATOKEN"]}" }
newdf = pd.DataFrame()
for index in range(1,8):
  url = f"https://api.themoviedb.org/3/tv/top_rated?language=en-US&page={index}"
  response = requests.get(url, headers=headers)
  data = response.json()
  ogdf = pd.DataFrame(data["results"],columns=["id", "name", "overview", "first_air_date", "vote_count", "vote_average"])
  newdf = pd.concat([newdf, ogdf], ignore_index=True)
newdf.shape
newdf.head()

,id,name,overview,first_air_date,vote_count,vote_average
0,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,17644,8.942
1,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,2023-09-29,797,8.799
2,64010,Reply 1988,Take a nostalgic trip back to the late 1980s t...,2015-11-06,207,8.800
3,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",2005-02-21,4793,8.757
4,94605,Arcane,Amid the stark discord of twin cities Piltover...,2021-11-06,5847,8.753

In [116]:
newdf.shape

(140, 6)

#Web Scraping

In [120]:
!pip install -q requests beautifulsoup4

In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
url = "https://www.zameen.com/Homes/Islamabad_DHA_Defence-3188-1.html"
#incase you cannot access the site because the site blacklists bots. so you add this header.
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"}
response = requests.get(url, headers=headers)

In [4]:
bs = BeautifulSoup(response.text, "lxml")

In [8]:
price = bs.find_all("span", class_="dc381b54")
print(len(price))

location = bs.find_all("div", class_="db1aca2f", attrs={"aria-label":"Location"})
print(len(location))

baths= bs.find_all("span", class_="_6d9b9b83", attrs={"aria-label":"Baths"})
print(len(baths))

beds= bs.find_all("span", class_="_6d9b9b83", attrs={"aria-label":"Beds"})
print(len(beds))

zameen = pd.DataFrame()
print(price)

for i in range(len(price)):
  zameen.loc[i, "price"] = price[i].text
print(location)
for i in range(len(location)):
  zameen.loc[i, "location"] = location[i].text
print(baths)
for i in range(len(baths)):
  zameen.loc[i, "baths"] = baths[i].text
print(beds)
for i in range(len(beds)):
  zameen.loc[i, "beds"] = beds[i].text

zameen

25
25
25
23
[<span aria-label="Price" class="dc381b54">13.9 Crore</span>, <span aria-label="Price" class="dc381b54">14.5 Crore</span>, <span aria-label="Price" class="dc381b54">15.25 Crore</span>, <span aria-label="Price" class="dc381b54">13.5 Crore</span>, <span aria-label="Price" class="dc381b54">14.5 Crore</span>, <span aria-label="Price" class="dc381b54">78.4 Lakh</span>, <span aria-label="Price" class="dc381b54">16 Crore</span>, <span aria-label="Price" class="dc381b54">10.9 Crore</span>, <span aria-label="Price" class="dc381b54">11.75 Crore</span>, <span aria-label="Price" class="dc381b54">1.03 Crore</span>, <span aria-label="Price" class="dc381b54">1.1 Crore</span>, <span aria-label="Price" class="dc381b54">14.5 Crore</span>, <span aria-label="Price" class="dc381b54">6 Crore</span>, <span aria-label="Price" class="dc381b54">6.6 Crore</span>, <span aria-label="Price" class="dc381b54">15.2 Crore</span>, <span aria-label="Price" class="dc381b54">12.75 Crore</span>, <span aria-label="Price" class="dc381b54">8 Crore</span>, <span aria-label="Price" class="dc381b54">6.3 Crore</span>, <span aria-label="Price" class="dc381b54">9.9 Crore</span>, <span aria-label="Price" class="dc381b54">10.9 Crore</span>, <span aria-label="Price" class="dc381b54">13.8 Crore</span>, <span aria-label="Price" class="dc381b54">12.9 Crore</span>, <span aria-label="Price" class="dc381b54">15 Crore</span>, <span aria-label="Price" class="dc381b54">12.8 Crore</span>, <span aria-label="Price" class="dc381b54">10.5 Crore</span>]
[<div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Phase 2 - Sector B, DHA Defence Phase 2</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">Goldcrest Views, DHA Defence Phase 2</div>, <div aria-label="Location" class="db1aca2f">DHA Phase 5 - Sector C, DHA Defence Phase 5</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 5, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">Grand Orchard, DHA Defence Phase 1</div>, <div aria-label="Location" class="db1aca2f">Al-Ghurair Giga - Block 14, Al-Ghurair Giga</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>, <div aria-label="Location" class="db1aca2f">DHA Defence Phase 2, DHA Defence</div>]
[<span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">1</span>, <span aria-label="Baths" class="_6d9b9b83">5</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">1</span>, <span aria-label="Baths" class="_6d9b9b83">2</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">5</span>, <span aria-label="Baths" class="_6d9b9b83">7</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">5</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>, <span aria-label="Baths" class="_6d9b9b83">6</span>]
[<span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">4</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">4</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">2</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">7</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">5</span>, <span aria-label="Beds" class="_6d9b9b83">7</span>, <span aria-label="Beds" class="_6d9b9b83">6</span>]

          price                                     location baths beds
0    13.9 Crore             DHA Defence Phase 2, DHA Defence     6    5
1    14.5 Crore             DHA Defence Phase 2, DHA Defence     6    5
2   15.25 Crore             DHA Defence Phase 2, DHA Defence     6    4
3    13.5 Crore  DHA Phase 2 - Sector B, DHA Defence Phase 2     6    5
4    14.5 Crore             DHA Defence Phase 2, DHA Defence     6    5
5     78.4 Lakh         Goldcrest Views, DHA Defence Phase 2     1    4
6      16 Crore  DHA Phase 5 - Sector C, DHA Defence Phase 5     5    5
7    10.9 Crore             DHA Defence Phase 5, DHA Defence     6    6
8   11.75 Crore             DHA Defence Phase 2, DHA Defence     6    2
9    1.03 Crore           Grand Orchard, DHA Defence Phase 1     1    6
10    1.1 Crore  Al-Ghurair Giga - Block 14, Al-Ghurair Giga     2    5
11   14.5 Crore             DHA Defence Phase 2, DHA Defence     6    6
12      6 Crore             DHA Defence Phase 2, DHA Defence     6    5
13    6.6 Crore             DHA Defence Phase 2, DHA Defence     6    7
14   15.2 Crore             DHA Defence Phase 2, DHA Defence     5    6
15  12.75 Crore             DHA Defence Phase 2, DHA Defence     7    5
16      8 Crore             DHA Defence Phase 2, DHA Defence     6    6
17    6.3 Crore             DHA Defence Phase 2, DHA Defence     6    6
18    9.9 Crore             DHA Defence Phase 2, DHA Defence     6    5
19   10.9 Crore             DHA Defence Phase 2, DHA Defence     6    5
20   13.8 Crore             DHA Defence Phase 2, DHA Defence     6    5
21   12.9 Crore             DHA Defence Phase 2, DHA Defence     6    7
22     15 Crore             DHA Defence Phase 2, DHA Defence     5    6
23   12.8 Crore             DHA Defence Phase 2, DHA Defence     6  NaN
24   10.5 Crore             DHA Defence Phase 2, DHA Defence     6  NaN